version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
      - CSRF_TRUSTED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
      - MEDIA_URL=/media/
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - db_data:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  media_data:
  db_data:
