services:
  - type: web
    name: attendance-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn gov_biometric.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: attendance-gov-backend.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: attendance_29g1
      - key: DB_USER
        value: attendance_29g1_user
      - key: DB_PASSWORD
        value: 76XChVT5BcG8G5ikX2H6BgS14InEtN4U
      - key: DB_HOST
        value: dpg-d32js8jipnbc73d8k890-a
      - key: DB_PORT
        value: "5432"
      - key: MEDIA_ROOT
        value: media/
      - key: MEDIA_URL
        value: /media/
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://attendance-gov.onrender.com,https://attendance-gov-backend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://attendance-gov.onrender.com,https://attendance-gov-backend.onrender.com

