services:
  - type: web
    name: attendance-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn gov_biometric.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    autoDeploy: true
    disk:
      name: media-and-db
      mountPath: /data
      sizeGB: 2
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: attendance-gov-backend.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.sqlite3
      - key: DB_NAME
        value: /data/db.sqlite3
      - key: MEDIA_ROOT
        value: /data/media
      - key: MEDIA_URL
        value: /media/
      - key: JWT_SECRET_KEY
        generateValue: true
      # Set CORS/CSRF to your frontend domain(s) once deployed
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:8080
      - key: CSRF_TRUSTED_ORIGINS
        value: http://localhost:8080

